CREATE TABLE professores 
(	ID_PROFESSORES INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOME_PROFESSOR VARCHAR(50) NOT NULL,
	EMAIL_PROFESSOR VARCHAR(100) NOT NULL
);

CREATE TABLE usuario 
(	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOME_USUARIO VARCHAR(50) NOT NULL,
	EMAIL_USUARIO VARCHAR(100) NOT NULL,
	SENHA_USUARIO VARCHAR(6) NOT NULL
);

INSERT INTO professores(NOME_PROFESSOR,EMAIL_PROFESSOR) VALUES('Denilce', 'denilce@email.com');
INSERT INTO professores(NOME_PROFESSOR,EMAIL_PROFESSOR) VALUES('Dimas', 'dimas@email.com');
INSERT INTO professores(NOME_PROFESSOR,EMAIL_PROFESSOR) VALUES('Jeff', 'jeff@email.com');
INSERT INTO professores(NOME_PROFESSOR,EMAIL_PROFESSOR) VALUES('Munari', 'munari@email.com');

SELECT * FROM professores;

INSERT INTO usuario(NOME_USUARIO,EMAIL_USUARIO,SENHA_USUARIO) VALUES('Clara', 'clara@email.com', 'clara123');
INSERT INTO usuario(NOME_USUARIO,EMAIL_USUARIO,SENHA_USUARIO) VALUES('Eros', 'eros@email.com', 'eros123');
INSERT INTO usuario(NOME_USUARIO,EMAIL_USUARIO,SENHA_USUARIO) VALUES('Luciana', 'luciana@email.com', 'luciana123');
INSERT INTO usuario(NOME_USUARIO,EMAIL_USUARIO,SENHA_USUARIO) VALUES('Filipe', 'filipe@email.com', 'fili123');